apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: openfaas-fn
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.name }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.envVariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
